version: "3.9"
services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    ports:
      - "8001:8001"

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    ports:
      - "8002:8002"

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    ports:
      - "8003:8003"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - auth-service
      - inventory-service
      - order-service
    ports:
      - "8000:8000"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8001
      INVENTORY_SERVICE_URL: http://inventory-service:8002
      ORDER_SERVICE_URL: http://order-service:8003

volumes:
  postgres_data:
